### PR TITLE
150&151--line chart adjustment

### PR DESCRIPTION
**Pull request by DarleneQing**
- Adjust overall display (remove navigation bar, and delete unnecessary margin and padding)
- Add "All feature" chart with legend
- replace previously played
- change hide/show button to arrow like

https://github.com/user-attachments/assets/bea2030e-a565-43fe-8fbb-51bb8eadb1fa

### CODE REVIEW

**Comment by maettuu** [comment]
can you please pull the latest state of the main branch just to make sure everything is working before merging :)

**Comment by DarleneQing** [comment]
> can you please pull the latest state of the main branch just to make sure everything is working before merging :)

The recommendation endpoint has been updated right? I think it doesn't work with the current FE as we haven't connect the voting. Other than that it's working well. Also my updated doesn't involved changes related to BE so I think it should be fine.

**Comment by DarleneQing** [comment]
> can you please pull the latest state of the main branch just to make sure everything is working before merging :)

Ahh nvm, I saw how it changed. Fixed it now :) Everything works on my side currently

**Comment by maettuu** [comment]
perfect thank you! @FE can you please review the changes and merge?

**Comment by DarleneQing** [comment]
Update on legend. Followed the suggestion from Ibra on Monday where the colored name of feature follows the end of line chart.

image

**Review by danielamormocea — APPROVED** [review]
Looks good, if we don't want to redirect to the correct tab when we still click on the petals. (Not sure if we still want to maintain that functionality - because when you click on the flower now, it still highlights the point in the graph - but if you click on a specific petal, shouldn't we still show the right tab? - it's not necessary with the new logic, just wondering if it makes sense to maintain that as well)

**Pull request merged**
